//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from nml.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="nmlParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public interface InmlListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="nmlParser.json"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJson([NotNull] nmlParser.JsonContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="nmlParser.json"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJson([NotNull] nmlParser.JsonContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="nmlParser.obj"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObj([NotNull] nmlParser.ObjContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="nmlParser.obj"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObj([NotNull] nmlParser.ObjContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="nmlParser.pair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPair([NotNull] nmlParser.PairContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="nmlParser.pair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPair([NotNull] nmlParser.PairContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="nmlParser.array"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArray([NotNull] nmlParser.ArrayContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="nmlParser.array"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArray([NotNull] nmlParser.ArrayContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="nmlParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValue([NotNull] nmlParser.ValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="nmlParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValue([NotNull] nmlParser.ValueContext context);
}
